# Generated by Django 5.2.17 on 2026-09-25 06:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RollLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollerNo', models.CharField(max_length=40, verbose_name='揉捻机号')),
                ('plannedRolls', models.PositiveIntegerField(blank=True, null=True, verbose_name='计划揉次')),
                ('openedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开单时刻')),
                ('closedAt', models.DateTimeField(blank=True, null=True, verbose_name='关闭时刻')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_links', to='gardens.witherbatch', verbose_name='关联批次')),
                ('openedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_roll_links', to=settings.AUTH_USER_MODEL, verbose_name='开单人')),
            ],
            options={
                'verbose_name': '揉捻衔接单',
                'verbose_name_plural': '揉捻衔接单',
                'ordering': ['-openedAt', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('closedAt__isnull', True)), fields=('batch',), name='uniq_open_roll_link_per_batch')],
            },
        ),
    ]
